---
# handlers file for setup-apache-role
- name: start apache
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: Start apache2 service
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"
